### ISSUE TITLE
License update?

### ISSUE THREAD

**Issue by nixel2007** [nixel2007/intellij-lsp#13]
Do we need/want to update the license owner with NOTICE to original author?

Original intellij-lsp uses apache license (it's ok), but doesn't have copyright boilerplates in files (common mistake with apache :) )

So... at least we should add license header in all scala files with gradle license plugin (also i'll add it as part of CI process).
Also i think that java files from #4 can be considered as new code (based on original work), and we can add intellij-lsp-community copyright

@intellij-lsp/all?

**Comment by NipunaRanasinghe** [comment]
Sure I'll work on those changes while you can complete the CI process
